# Copyright 2026 Michael Ellis
# SPDX-License-Identifier: Apache-2.0

"""Tests for the WHM dynamic generalized linear model filter."""

import jax
import jax.numpy as jnp
import numpy as np
import pytest
from jax.scipy import stats as jstats
from jax.scipy.special import digamma, polygamma

import smcx
from smcx import DGLMFamily, dglm_filter, kalman_filter, poisson


def _normal_family(variance: float) -> DGLMFamily:
    """Known-variance normal family built through the public contract.

    West, Harrison & Migon (1985, sec. 2.2) prove the DGLM step with a
    normal observation and identity link reduces exactly to the Kalman
    step: a normal is determined by its two moments, and the exact
    conditional mean is linear, so both approximations vanish.
    """

    def match_moments(forecast_mean, forecast_variance):
        return forecast_mean, forecast_variance

    def log_forecast(emission, mean, var):
        return jstats.norm.logpdf(
            emission, loc=mean, scale=jnp.sqrt(var + variance)
        )

    def update(emission, mean, var):
        gain = var / (var + variance)
        return mean + gain * (emission - mean), var * variance / (
            var + variance
        )

    def posterior_moments(mean, var):
        return mean, var

    return DGLMFamily(
        match_moments=match_moments,
        log_forecast=log_forecast,
        update=update,
        posterior_moments=posterior_moments,
    )


def _trend_model():
    """Locally linear trend used across the tests."""
    transition = jnp.array([[1.0, 1.0], [0.0, 1.0]])
    observation = jnp.array([1.0, 0.0])
    initial_mean = jnp.array([0.3, 0.1])
    initial_cov = jnp.array([[0.5, 0.1], [0.1, 0.2]])
    evolution = jnp.diag(jnp.array([0.05, 0.01]))
    return transition, observation, initial_mean, initial_cov, evolution


_CPU_X64 = jax.default_backend() == "cpu" and jax.config.read("jax_enable_x64")


class TestKalmanReduction:
    """The normal family must reproduce kalman_filter exactly."""

    def test_normal_family_matches_kalman_filter(self):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        variance = 0.3
        emissions = jnp.array([0.2, -0.4, 0.9, 0.1, 0.5])

        dglm = dglm_filter(
            mean_0,
            cov_0,
            transition,
            observation,
            emissions,
            family=_normal_family(variance),
            transition_covariance=evolution,
        )
        kalman = kalman_filter(
            mean_0,
            cov_0,
            transition,
            evolution,
            observation[None, :],
            jnp.array([[variance]]),
            emissions[:, None],
        )
        # The identity is exact; the tolerance is roundoff of the two
        # arithmetic paths in the working dtype (f32 on Metal).
        eps = float(jnp.finfo(dglm.filtered_means.dtype).eps)
        np.testing.assert_allclose(
            dglm.filtered_means, kalman.filtered_means, rtol=1e3 * eps
        )
        np.testing.assert_allclose(
            dglm.filtered_covariances,
            kalman.filtered_covariances,
            rtol=1e3 * eps,
            atol=1e2 * eps,
        )
        np.testing.assert_allclose(
            dglm.marginal_loglik, kalman.marginal_loglik, rtol=1e3 * eps
        )


@pytest.mark.skipif(not _CPU_X64, reason="frozen CPU/x64 arithmetic contract")
class TestExactRecursion:
    """Frozen 50-digit mpmath reference for the Poisson recursion.

    Generated by scratchpad ``dglm_golden.py`` (mpmath dps=50):
    locally linear trend, library emission alignment, exact
    digamma/trigamma moment matching by root finding.
    """

    #: per step: mean, covariance, alpha*, beta*, log increment
    GOLDEN = (
        (
            (0.18677224597524215, 0.077354449195048429),
            (
                (0.33474812372436609, 0.066949624744873219),
                (0.066949624744873219, 0.19338992494897464),
            ),
            3.4599529483523074,
            2.467158327402094,
            -1.2814597378730204,
        ),
        (
            (-0.4011612274045365, -0.16589230013495026),
            (
                (0.71203729816308718, 0.26033954969384786),
                (0.26033954969384786, 0.20338992494897464),
            ),
            1.8492184499065385,
            2.0581445514224159,
            -1.2302627009253629,
        ),
        (
            (0.53039220578523253, 0.17655825381171205),
            (
                (0.27813004908155984, 0.086788609664228937),
                (0.086788609664228937, 0.095768065300394347),
            ),
            4.0725728768886783,
            2.1087921630642396,
            -2.7982362547674957,
        ),
    )
    LOGLIK = -5.3099586935658789

    def test_matches_mpmath_reference(self):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        posterior = dglm_filter(
            mean_0,
            cov_0,
            transition,
            observation,
            jnp.array([1, 0, 3]),
            family=poisson(),
            transition_covariance=evolution,
        )
        means, covs, alphas, betas, incs = zip(*self.GOLDEN, strict=True)
        np.testing.assert_allclose(
            posterior.filtered_means, np.array(means), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.filtered_covariances, np.array(covs), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.conjugate_alphas, np.array(alphas), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.conjugate_betas, np.array(betas), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.log_evidence_increments, np.array(incs), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.marginal_loglik, self.LOGLIK, rtol=1e-11
        )

    def test_discount_equals_its_implied_evolution_covariance(self):
        transition, observation, mean_0, cov_0, _ = _trend_model()
        emissions = jnp.array([1, 0, 3, 2])
        delta = 0.9
        discounted = dglm_filter(
            mean_0,
            cov_0,
            transition,
            observation,
            emissions,
            family=poisson(),
            discount=delta,
        )
        propagated = jax.vmap(lambda cov: transition @ cov @ transition.T)(
            discounted.filtered_covariances[:-1]
        )
        implied = propagated * (1.0 - delta) / delta
        explicit = dglm_filter(
            mean_0,
            cov_0,
            transition,
            observation,
            emissions,
            family=poisson(),
            transition_covariance=implied,
        )
        np.testing.assert_allclose(
            explicit.filtered_means, discounted.filtered_means, rtol=1e-12
        )
        np.testing.assert_allclose(
            explicit.marginal_loglik,
            discounted.marginal_loglik,
            rtol=1e-12,
        )


class TestMomentMatching:
    """The exact digamma/trigamma match and its closed-form limit."""

    @pytest.mark.parametrize("q", [1e-4, 0.01, 0.5, 4.0, 20.0])
    def test_poisson_match_solves_moment_equations(self, q):
        family = poisson()
        f = 0.7
        alpha, beta = (
            jnp.asarray(value)
            for value in family.match_moments(jnp.asarray(f), jnp.asarray(q))
        )
        eps = float(jnp.finfo(alpha.dtype).eps)
        np.testing.assert_allclose(
            np.asarray(polygamma(1, alpha)), q, rtol=1e3 * eps
        )
        np.testing.assert_allclose(
            np.asarray(digamma(alpha) - jnp.log(beta)), f, atol=1e3 * eps
        )

    def test_small_q_limit_recovers_whm_closed_form(self):
        # WHM (1985, sec. 5): mode/curvature matching gives
        # alpha = 1/q, beta = exp(-f)/q — the q -> 0 limit of the
        # exact match (trigamma(a) = 1/a + 1/(2a^2) + O(a^-3)).
        family = poisson()
        f, q = -0.4, 1e-6
        alpha, beta = (
            jnp.asarray(value)
            for value in family.match_moments(jnp.asarray(f), jnp.asarray(q))
        )
        np.testing.assert_allclose(np.asarray(alpha * q), 1.0, rtol=1e-5)
        np.testing.assert_allclose(
            np.asarray(beta * q * jnp.exp(f)), 1.0, rtol=1e-5
        )


class TestBoundaries:
    """Entry validation at the filter boundary."""

    def test_rejects_both_evolution_specifications(self):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        with pytest.raises(ValueError, match="exactly one"):
            dglm_filter(
                mean_0,
                cov_0,
                transition,
                observation,
                jnp.array([1, 0, 3]),
                family=poisson(),
                transition_covariance=evolution,
                discount=0.9,
            )

    def test_rejects_neither_evolution_specification(self):
        transition, observation, mean_0, cov_0, _ = _trend_model()
        with pytest.raises(ValueError, match="exactly one"):
            dglm_filter(
                mean_0,
                cov_0,
                transition,
                observation,
                jnp.array([1, 0, 3]),
                family=poisson(),
            )

    @pytest.mark.parametrize("bad", [0.0, 1.2, -0.5])
    def test_rejects_discount_outside_unit_interval(self, bad):
        transition, observation, mean_0, cov_0, _ = _trend_model()
        with pytest.raises(ValueError):
            dglm_filter(
                mean_0,
                cov_0,
                transition,
                observation,
                jnp.array([1, 0, 3]),
                family=poisson(),
                discount=bad,
            )

    def test_rejects_multivariate_emissions(self):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        with pytest.raises(ValueError, match="univariate"):
            dglm_filter(
                mean_0,
                cov_0,
                transition,
                observation,
                jnp.ones((4, 2)),
                family=poisson(),
                transition_covariance=evolution,
            )

    def test_family_is_required(self):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        with pytest.raises(TypeError):
            dglm_filter(  # ty: ignore[missing-argument]
                mean_0,
                cov_0,
                transition,
                observation,
                jnp.array([1, 0, 3]),
                transition_covariance=evolution,
            )


class TestTransforms:
    """jit, grad, and vmap coverage."""

    def _posterior(self, filter_fn=dglm_filter):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        return filter_fn(
            mean_0,
            cov_0,
            transition,
            observation,
            jnp.array([1, 0, 3]),
            family=poisson(),
            transition_covariance=evolution,
        )

    def test_jit_matches_eager(self):
        eager = self._posterior()
        jitted = self._posterior(jax.jit(dglm_filter, static_argnames="family"))
        eps = 32 * float(jnp.finfo(eager.filtered_means.dtype).eps)
        np.testing.assert_allclose(
            jitted.filtered_means, eager.filtered_means, rtol=eps
        )
        np.testing.assert_allclose(
            jitted.marginal_loglik, eager.marginal_loglik, rtol=eps
        )

    def test_gradient_through_marginal_loglik_is_finite(self):
        transition, observation, _, cov_0, evolution = _trend_model()

        def loglik(mean_0):
            return dglm_filter(
                mean_0,
                cov_0,
                transition,
                observation,
                jnp.array([1, 0, 3]),
                family=poisson(),
                transition_covariance=evolution,
            ).marginal_loglik

        gradient = jax.grad(loglik)(jnp.array([0.3, 0.1]))
        assert bool(jnp.all(jnp.isfinite(gradient)))

    def test_vmap_over_emission_batches(self):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        batches = jnp.array([[1, 0, 3], [0, 2, 1]])

        def run(emissions):
            return dglm_filter(
                mean_0,
                cov_0,
                transition,
                observation,
                emissions,
                family=poisson(),
                transition_covariance=evolution,
            ).marginal_loglik

        batched = jax.vmap(run)(batches)
        eps = float(jnp.finfo(batched.dtype).eps)
        np.testing.assert_allclose(batched[0], run(batches[0]), rtol=32 * eps)
        np.testing.assert_allclose(batched[1], run(batches[1]), rtol=32 * eps)


def test_family_record_is_exported():
    assert smcx.DGLMFamily is DGLMFamily
    assert isinstance(poisson(), DGLMFamily)
