# Copyright 2026 Michael Ellis
# SPDX-License-Identifier: Apache-2.0

"""Tests for the WHM dynamic generalized linear model filter."""

import math
import weakref

import jax
import jax.numpy as jnp
import numpy as np
import pytest
from jax.scipy import stats as jstats
from jax.scipy.special import digamma, polygamma
from jaxtyping import TypeCheckError

import smcx
import smcx.dglm as dglm_module
from smcx import (
    DGLMFamily,
    bernoulli,
    binomial,
    dglm_filter,
    kalman_filter,
    poisson,
)


def _normal_family(variance: float) -> DGLMFamily:
    """Known-variance normal family built through the public contract.

    West, Harrison & Migon (1985, sec. 2.2) prove the DGLM step with a
    normal observation and identity link reduces exactly to the Kalman
    step: a normal is determined by its two moments, and the exact
    conditional mean is linear, so both approximations vanish.
    """

    def match_moments(forecast_mean, forecast_variance):
        return forecast_mean, forecast_variance

    def log_forecast(emission, mean, var):
        return jstats.norm.logpdf(
            emission, loc=mean, scale=jnp.sqrt(var + variance)
        )

    def update(emission, mean, var):
        gain = var / (var + variance)
        return mean + gain * (emission - mean), var * variance / (
            var + variance
        )

    def posterior_moments(mean, var):
        return mean, var

    return DGLMFamily(
        match_moments=match_moments,
        log_forecast=log_forecast,
        update=update,
        posterior_moments=posterior_moments,
    )


def _trend_model():
    """Locally linear trend used across the tests."""
    transition = jnp.array([[1.0, 1.0], [0.0, 1.0]])
    observation = jnp.array([1.0, 0.0])
    initial_mean = jnp.array([0.3, 0.1])
    initial_cov = jnp.array([[0.5, 0.1], [0.1, 0.2]])
    evolution = jnp.diag(jnp.array([0.05, 0.01]))
    return transition, observation, initial_mean, initial_cov, evolution


_CPU_X64 = jax.default_backend() == "cpu" and jax.config.read("jax_enable_x64")


class TestKalmanReduction:
    """The normal family must reproduce kalman_filter exactly."""

    def test_normal_family_matches_kalman_filter(self):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        variance = 0.3
        emissions = jnp.array([0.2, -0.4, 0.9, 0.1, 0.5])

        dglm = dglm_filter(
            mean_0,
            cov_0,
            transition,
            observation,
            emissions,
            family=_normal_family(variance),
            transition_covariance=evolution,
        )
        kalman = kalman_filter(
            mean_0,
            cov_0,
            transition,
            evolution,
            observation[None, :],
            jnp.array([[variance]]),
            emissions[:, None],
        )
        # The identity is exact; the tolerance is roundoff of the two
        # arithmetic paths in the working dtype (f32 on Metal).
        eps = float(jnp.finfo(dglm.filtered_means.dtype).eps)
        np.testing.assert_allclose(
            dglm.filtered_means, kalman.filtered_means, rtol=1e3 * eps
        )
        np.testing.assert_allclose(
            dglm.filtered_covariances,
            kalman.filtered_covariances,
            rtol=1e3 * eps,
            atol=1e2 * eps,
        )
        np.testing.assert_allclose(
            dglm.marginal_loglik, kalman.marginal_loglik, rtol=1e3 * eps
        )


@pytest.mark.skipif(not _CPU_X64, reason="frozen CPU/x64 arithmetic contract")
class TestExactRecursion:
    """Frozen 50-digit mpmath reference for the Poisson recursion.

    Generated by scratchpad ``dglm_golden.py`` (mpmath dps=50):
    locally linear trend, library emission alignment, exact
    digamma/trigamma moment matching by root finding.
    """

    #: per step: mean, covariance, alpha*, beta*, log increment
    GOLDEN = (
        (
            (0.18677224597524215, 0.077354449195048429),
            (
                (0.33474812372436609, 0.066949624744873219),
                (0.066949624744873219, 0.19338992494897464),
            ),
            3.4599529483523074,
            2.467158327402094,
            -1.2814597378730204,
        ),
        (
            (-0.4011612274045365, -0.16589230013495026),
            (
                (0.71203729816308718, 0.26033954969384786),
                (0.26033954969384786, 0.20338992494897464),
            ),
            1.8492184499065385,
            2.0581445514224159,
            -1.2302627009253629,
        ),
        (
            (0.53039220578523253, 0.17655825381171205),
            (
                (0.27813004908155984, 0.086788609664228937),
                (0.086788609664228937, 0.095768065300394347),
            ),
            4.0725728768886783,
            2.1087921630642396,
            -2.7982362547674957,
        ),
    )
    LOGLIK = -5.3099586935658789

    def test_matches_mpmath_reference(self):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        posterior = dglm_filter(
            mean_0,
            cov_0,
            transition,
            observation,
            jnp.array([1, 0, 3]),
            family=poisson(),
            transition_covariance=evolution,
        )
        means, covs, alphas, betas, incs = zip(*self.GOLDEN, strict=True)
        np.testing.assert_allclose(
            posterior.filtered_means, np.array(means), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.filtered_covariances, np.array(covs), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.conjugate_alphas, np.array(alphas), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.conjugate_betas, np.array(betas), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.log_evidence_increments, np.array(incs), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.marginal_loglik, self.LOGLIK, rtol=1e-11
        )

    def test_discount_equals_its_implied_evolution_covariance(self):
        transition, observation, mean_0, cov_0, _ = _trend_model()
        emissions = jnp.array([1, 0, 3, 2])
        delta = 0.9
        discounted = dglm_filter(
            mean_0,
            cov_0,
            transition,
            observation,
            emissions,
            family=poisson(),
            discount=delta,
        )
        propagated = jax.vmap(lambda cov: transition @ cov @ transition.T)(
            discounted.filtered_covariances[:-1]
        )
        implied = propagated * (1.0 - delta) / delta
        explicit = dglm_filter(
            mean_0,
            cov_0,
            transition,
            observation,
            emissions,
            family=poisson(),
            transition_covariance=implied,
        )
        np.testing.assert_allclose(
            explicit.filtered_means, discounted.filtered_means, rtol=1e-12
        )
        np.testing.assert_allclose(
            explicit.marginal_loglik,
            discounted.marginal_loglik,
            rtol=1e-12,
        )


@pytest.mark.skipif(not _CPU_X64, reason="frozen CPU/x64 arithmetic contract")
class TestBernoulliExact:
    """Frozen 50-digit mpmath reference for the Bernoulli recursion.

    Generated by scratchpad ``dglm_bern_golden.py`` (mpmath dps=50):
    local level, library emission alignment, exact 2-D
    digamma/trigamma moment matching by root finding.
    """

    #: per step: mean, covariance, alpha*, beta*, log increment
    GOLDEN = (
        (
            0.085210222111629541,
            0.51865512920303494,
            4.5061856920703428,
            4.1772128104810881,
            -0.78453321345430482,
        ),
        (
            -0.1865481037215118,
            0.52480254154340313,
            3.964749663924763,
            4.6797400665987194,
            -0.73114297602686766,
        ),
        (
            0.099141127065022189,
            0.52318420495600165,
            4.5003069497820748,
            4.120704542013415,
            -0.77805843800691022,
        ),
    )
    LOGLIK = -2.2937346274880827

    def test_matches_mpmath_reference(self):
        posterior = dglm_filter(
            jnp.array([-0.2]),
            jnp.array([[0.6]]),
            jnp.eye(1),
            jnp.ones(1),
            jnp.array([1, 0, 1]),
            family=bernoulli(),
            transition_covariance=jnp.array([[0.08]]),
        )
        means, covs, alphas, betas, incs = zip(*self.GOLDEN, strict=True)
        np.testing.assert_allclose(
            posterior.filtered_means[:, 0], np.array(means), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.filtered_covariances[:, 0, 0],
            np.array(covs),
            rtol=1e-11,
        )
        np.testing.assert_allclose(
            posterior.conjugate_alphas, np.array(alphas), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.conjugate_betas, np.array(betas), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.log_evidence_increments, np.array(incs), rtol=1e-11
        )
        np.testing.assert_allclose(
            posterior.marginal_loglik, self.LOGLIK, rtol=1e-11
        )


@pytest.mark.skipif(not _CPU_X64, reason="frozen CPU/x64 arithmetic contract")
class TestPinnedPyBATS:
    """Frozen pybats 0.0.5 traces (Apache-2.0, from West's group).

    Generated by scratchpad ``pybats_dglm_ref.py`` with
    pybats==0.0.5, scipy 1.18.0, numpy 2.5.1 under the source-dive
    fixture rules: ``interpolate=False`` (the exact LM moment-match
    path, not the ~3-digit spline), ``adapt_discount=False``,
    ``rho=1``, explicit priors, regimes away from pybats' clamps and
    small-q solver branches. pybats' first-observation convention
    (a0/R0 condition directly; evolve and discount afterwards)
    matches the library's alignment, and its linear-Bayes core
    matches WHM verbatim. Tolerance 1e-6 reflects pybats' scipy-LM
    moment-match tolerance (~1e-8) against our Newton solves.
    """

    #: rows of (y, m, C, alpha*, beta*, log forecast density)
    POISSON = (
        (
            2,
            0.57996394528233819,
            0.22291802495959556,
            4.9675403021436102,
            2.5066415288810977,
            -1.5758135031305145,
        ),
        (
            1,
            0.44015558401584509,
            0.19018501397186624,
            5.7422912332612865,
            3.3807912023809679,
            -1.324601330157178,
        ),
        (
            0,
            0.16905553860425826,
            0.20019475154933286,
            5.4785718376262116,
            4.211239193300103,
            -1.4852410739711064,
        ),
        (
            3,
            0.43610790284757006,
            0.12922080072093023,
            8.2279563050911584,
            4.9999714296914526,
            -2.3256232651807958,
        ),
        (
            1,
            0.37258225562860359,
            0.11975454289265927,
            8.8404602949523508,
            5.749619219394444,
            -1.18790640090414,
        ),
        (
            4,
            0.61280717490055325,
            0.083826546128416723,
            12.422418637996209,
            6.4617885338769039,
            -2.9042123196181011,
        ),
    )
    BERNOULLI = (
        (
            1,
            0.26255546729383306,
            0.53106462659411691,
            4.8087190120511671,
            3.8087190120511671,
            -0.69314718055994529,
        ),
        (
            0,
            -0.025365426770830535,
            0.50717336608780128,
            4.3731389965618117,
            4.4731762112943816,
            -0.81497451135600618,
        ),
        (
            0,
            -0.2709748822250726,
            0.50320195771124987,
            3.9814710264055235,
            5.0715044872786015,
            -0.6820290681198653,
        ),
        (
            1,
            0.0045923573020385522,
            0.48317598284524077,
            4.6288783881424216,
            4.6098692760059308,
            -0.81992473331603166,
        ),
        (
            1,
            0.24201857629912873,
            0.48049099369412485,
            5.2118347511243419,
            4.1947265503864264,
            -0.69111414764078161,
        ),
        (
            0,
            -0.019691480451280191,
            0.46538672807805836,
            4.7363928832475111,
            4.8210224414634997,
            -0.80628015487168525,
        ),
    )

    def _assert_trace(self, posterior, rows):
        ys, means, covs, alphas, betas, incs = zip(*rows, strict=True)
        del ys
        np.testing.assert_allclose(
            posterior.filtered_means[:, 0], np.array(means), rtol=1e-6
        )
        np.testing.assert_allclose(
            posterior.filtered_covariances[:, 0, 0],
            np.array(covs),
            rtol=1e-6,
        )
        np.testing.assert_allclose(
            posterior.conjugate_alphas, np.array(alphas), rtol=1e-6
        )
        np.testing.assert_allclose(
            posterior.conjugate_betas, np.array(betas), rtol=1e-6
        )
        np.testing.assert_allclose(
            posterior.log_evidence_increments, np.array(incs), rtol=1e-6
        )

    def test_matches_pinned_pybats_poisson(self):
        posterior = dglm_filter(
            jnp.array([0.5]),
            jnp.array([[0.4]]),
            jnp.eye(1),
            jnp.ones(1),
            jnp.array([row[0] for row in self.POISSON]),
            family=poisson(),
            discount=0.95,
        )
        self._assert_trace(posterior, self.POISSON)

    def test_matches_pinned_pybats_bernoulli(self):
        posterior = dglm_filter(
            jnp.array([0.0]),
            jnp.array([[0.6]]),
            jnp.eye(1),
            jnp.ones(1),
            jnp.array([row[0] for row in self.BERNOULLI]),
            family=bernoulli(),
            discount=0.9,
        )
        self._assert_trace(posterior, self.BERNOULLI)


class TestBinomialFamily:
    """Beta moment matching, conjugate algebra, and the trials knob."""

    @pytest.mark.parametrize("q", [0.01, 0.5, 4.0])
    @pytest.mark.parametrize("f", [-1.5, 0.0, 2.0])
    def test_beta_match_solves_moment_equations(self, f, q):
        family = binomial(trials=5)
        alpha, beta = (
            jnp.asarray(value)
            for value in family.match_moments(jnp.asarray(f), jnp.asarray(q))
        )
        eps = float(jnp.finfo(alpha.dtype).eps)
        np.testing.assert_allclose(
            np.asarray(digamma(alpha) - digamma(beta)), f, atol=1e4 * eps
        )
        np.testing.assert_allclose(
            np.asarray(polygamma(1, alpha) + polygamma(1, beta)),
            q,
            rtol=1e4 * eps,
        )

    def test_conjugate_update_algebra(self):
        family = binomial(trials=5)
        alpha, beta = family.update(
            jnp.asarray(3.0), jnp.asarray(2.0), jnp.asarray(4.0)
        )
        np.testing.assert_allclose(np.asarray(alpha), 5.0)
        np.testing.assert_allclose(np.asarray(beta), 6.0)

    def test_binomial_single_trial_equals_bernoulli(self):
        emissions = jnp.array([1, 0, 1, 1])
        common = dict(
            transition_covariance=jnp.array([[0.05]]),
        )
        one = dglm_filter(
            jnp.array([0.2]),
            jnp.array([[0.4]]),
            jnp.eye(1),
            jnp.ones(1),
            emissions,
            family=binomial(trials=1),
            **common,
        )
        bern = dglm_filter(
            jnp.array([0.2]),
            jnp.array([[0.4]]),
            jnp.eye(1),
            jnp.ones(1),
            emissions,
            family=bernoulli(),
            **common,
        )
        np.testing.assert_allclose(
            one.filtered_means, bern.filtered_means, rtol=1e-14
        )
        np.testing.assert_allclose(
            one.marginal_loglik, bern.marginal_loglik, rtol=1e-14
        )

    def test_rejects_nonpositive_trials(self):
        with pytest.raises(ValueError, match="positive integer"):
            binomial(trials=0)


class TestDispersionDiscount:
    """Berry and West's random-effects discount rho."""

    def _run(self, **kwargs):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        return dglm_filter(
            mean_0,
            cov_0,
            transition,
            observation,
            jnp.array([1, 0, 3]),
            family=poisson(),
            transition_covariance=evolution,
            **kwargs,
        )

    def test_unit_dispersion_is_a_no_op(self):
        default = self._run()
        explicit = self._run(dispersion_discount=1.0)
        np.testing.assert_array_equal(
            np.asarray(default.filtered_means),
            np.asarray(explicit.filtered_means),
        )
        np.testing.assert_array_equal(
            np.asarray(default.marginal_loglik),
            np.asarray(explicit.marginal_loglik),
        )

    def test_dispersion_inflates_matched_prior(self):
        # First step: f = F'm0, q = (F'C0F)/rho before matching.
        _, observation, mean_0, cov_0, _ = _trend_model()
        rho = 0.5
        posterior = self._run(dispersion_discount=rho)
        f = float(observation @ mean_0)
        q = float(observation @ cov_0 @ observation) / rho
        alpha, beta = poisson().match_moments(jnp.asarray(f), jnp.asarray(q))
        eps = float(jnp.finfo(posterior.conjugate_alphas.dtype).eps)
        np.testing.assert_allclose(
            float(posterior.conjugate_alphas[0]),
            float(jnp.asarray(alpha)) + 1.0,
            rtol=1e3 * eps,
        )
        np.testing.assert_allclose(
            float(posterior.conjugate_betas[0]),
            float(jnp.asarray(beta)) + 1.0,
            rtol=1e3 * eps,
        )

    @pytest.mark.parametrize("bad", [0.0, 1.5, -0.2])
    def test_rejects_dispersion_outside_unit_interval(self, bad):
        with pytest.raises(ValueError):
            self._run(dispersion_discount=bad)


class TestMomentMatching:
    """The exact digamma/trigamma match and its closed-form limit."""

    @pytest.mark.parametrize("q", [1e-4, 0.01, 0.5, 4.0, 20.0])
    def test_poisson_match_solves_moment_equations(self, q):
        family = poisson()
        f = 0.7
        alpha, beta = (
            jnp.asarray(value)
            for value in family.match_moments(jnp.asarray(f), jnp.asarray(q))
        )
        eps = float(jnp.finfo(alpha.dtype).eps)
        np.testing.assert_allclose(
            np.asarray(polygamma(1, alpha)), q, rtol=1e3 * eps
        )
        np.testing.assert_allclose(
            np.asarray(digamma(alpha) - jnp.log(beta)), f, atol=1e3 * eps
        )

    def test_small_q_limit_recovers_whm_closed_form(self):
        # WHM (1985, sec. 5): mode/curvature matching gives
        # alpha = 1/q, beta = exp(-f)/q — the q -> 0 limit of the
        # exact match (trigamma(a) = 1/a + 1/(2a^2) + O(a^-3)).
        family = poisson()
        f, q = -0.4, 1e-6
        alpha, beta = (
            jnp.asarray(value)
            for value in family.match_moments(jnp.asarray(f), jnp.asarray(q))
        )
        np.testing.assert_allclose(np.asarray(alpha * q), 1.0, rtol=1e-5)
        np.testing.assert_allclose(
            np.asarray(beta * q * jnp.exp(f)), 1.0, rtol=1e-5
        )


class TestBoundaries:
    """Entry validation at the filter boundary."""

    def test_rejects_both_evolution_specifications(self):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        with pytest.raises(ValueError, match="exactly one"):
            dglm_filter(
                mean_0,
                cov_0,
                transition,
                observation,
                jnp.array([1, 0, 3]),
                family=poisson(),
                transition_covariance=evolution,
                discount=0.9,
            )

    def test_rejects_neither_evolution_specification(self):
        transition, observation, mean_0, cov_0, _ = _trend_model()
        with pytest.raises(ValueError, match="exactly one"):
            dglm_filter(
                mean_0,
                cov_0,
                transition,
                observation,
                jnp.array([1, 0, 3]),
                family=poisson(),
            )

    @pytest.mark.parametrize("bad", [0.0, 1.2, -0.5])
    def test_rejects_discount_outside_unit_interval(self, bad):
        transition, observation, mean_0, cov_0, _ = _trend_model()
        with pytest.raises(ValueError):
            dglm_filter(
                mean_0,
                cov_0,
                transition,
                observation,
                jnp.array([1, 0, 3]),
                family=poisson(),
                discount=bad,
            )

    def test_rejects_multivariate_emissions(self):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        with pytest.raises(ValueError, match="univariate"):
            dglm_filter(
                mean_0,
                cov_0,
                transition,
                observation,
                jnp.ones((4, 2)),
                family=poisson(),
                transition_covariance=evolution,
            )

    def test_family_is_required(self):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        with pytest.raises(TypeError):
            dglm_filter(  # ty: ignore[missing-argument]
                mean_0,
                cov_0,
                transition,
                observation,
                jnp.array([1, 0, 3]),
                transition_covariance=evolution,
            )


class TestTransforms:
    """jit, grad, and vmap coverage."""

    def _posterior(self, filter_fn=dglm_filter):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        return filter_fn(
            mean_0,
            cov_0,
            transition,
            observation,
            jnp.array([1, 0, 3]),
            family=poisson(),
            transition_covariance=evolution,
        )

    def test_jit_matches_eager(self):
        eager = self._posterior()
        jitted = self._posterior(jax.jit(dglm_filter, static_argnames="family"))
        eps = 32 * float(jnp.finfo(eager.filtered_means.dtype).eps)
        np.testing.assert_allclose(
            jitted.filtered_means, eager.filtered_means, rtol=eps
        )
        np.testing.assert_allclose(
            jitted.marginal_loglik, eager.marginal_loglik, rtol=eps
        )

    def test_gradient_through_marginal_loglik_is_finite(self):
        transition, observation, _, cov_0, evolution = _trend_model()

        def loglik(mean_0):
            return dglm_filter(
                mean_0,
                cov_0,
                transition,
                observation,
                jnp.array([1, 0, 3]),
                family=poisson(),
                transition_covariance=evolution,
            ).marginal_loglik

        gradient = jax.grad(loglik)(jnp.array([0.3, 0.1]))
        assert bool(jnp.all(jnp.isfinite(gradient)))

    def test_vmap_over_emission_batches(self):
        transition, observation, mean_0, cov_0, evolution = _trend_model()
        batches = jnp.array([[1, 0, 3], [0, 2, 1]])

        def run(emissions):
            return dglm_filter(
                mean_0,
                cov_0,
                transition,
                observation,
                emissions,
                family=poisson(),
                transition_covariance=evolution,
            ).marginal_loglik

        batched = jax.vmap(run)(batches)
        eps = float(jnp.finfo(batched.dtype).eps)
        np.testing.assert_allclose(batched[0], run(batches[0]), rtol=32 * eps)
        np.testing.assert_allclose(batched[1], run(batches[1]), rtol=32 * eps)


class TestParticleCorroboration:
    """The linear-Bayes moments agree with a bootstrap filter.

    Closing the DGLM's moments-only evolution with a Gaussian gives a
    fully specified model that a particle filter targets exactly (up
    to Monte Carlo error). The DGLM filtered means must then sit
    within the Monte Carlo band plus a small linear-Bayes allowance.
    Tier-2 stochastic contract: fixed key, band derived below.
    """

    def test_poisson_means_within_particle_band(self):
        import jax.random as jr
        from jax.scipy.special import gammaln

        counts = jnp.array([1, 0, 2, 1, 3])
        mean_0, cov_0, evolution = 0.0, 0.3, 0.05

        def sample_initial(key, num_particles):
            noise = jr.normal(key, (num_particles, 1))
            return mean_0 + jnp.sqrt(cov_0) * noise

        def sample_transition(key, state):
            return state + jnp.sqrt(evolution) * jr.normal(key, state.shape)

        def log_observation(count, state):
            log_rate = state[0]
            return (
                count[0] * log_rate
                - jnp.exp(log_rate)
                - gammaln(count[0] + 1.0)
            )

        particle = smcx.bootstrap_filter(
            jr.key(7),
            sample_initial,
            sample_transition,
            log_observation,
            counts[:, None].astype(jnp.float32),
            num_particles=16_384,
        )
        dglm = dglm_filter(
            jnp.array([mean_0]),
            jnp.array([[cov_0]]),
            jnp.eye(1),
            jnp.ones(1),
            counts,
            family=poisson(),
            transition_covariance=jnp.array([[evolution]]),
        )
        particle_means = np.asarray(smcx.weighted_mean(particle))[:, 0]
        dglm_means = np.asarray(dglm.filtered_means)[:, 0]
        # Band, calibrated 2026-07-28: the linear-Bayes discrepancy
        # against a 10^6-particle run is at most 0.048 across steps,
        # and the Monte Carlo standard error at N = 16384 (std over
        # 20 keys) is at most 0.004. Bias plus five standard errors
        # is 0.068; rounded up to 0.08.
        np.testing.assert_allclose(dglm_means, particle_means, atol=0.08)


def test_family_record_is_exported():
    assert smcx.DGLMFamily is DGLMFamily
    assert isinstance(poisson(), DGLMFamily)


def _dtype_rtol(double: float, single: float) -> float:
    """Pick a tolerance for the working dtype (#290 float32 leg)."""
    return double if jnp.asarray(0.0).dtype == jnp.float64 else single


class TestMomentMatchingDomain:
    """The moment matches hold across the full input domain (#282)."""

    @pytest.mark.parametrize(
        "variance",
        [1e-6, 1e-4, 1.0, 20.0, 30.0, 60.0, 100.0, 1e3, 1e6],
    )
    def test_inverse_trigamma_inverts_trigamma(self, variance):
        alpha = dglm_module._inverse_trigamma(jnp.asarray(variance))
        recovered = float(dglm_module._trigamma_safe(alpha))
        np.testing.assert_allclose(
            recovered, variance, rtol=_dtype_rtol(1e-8, 1e-5)
        )

    def test_safe_polygammas_match_asymptotic_closed_forms(self):
        argument = jnp.asarray(1e12)
        np.testing.assert_allclose(
            float(dglm_module._digamma_safe(argument)),
            math.log(1e12) - 5e-13,
            rtol=_dtype_rtol(1e-12, 1e-7),
        )
        np.testing.assert_allclose(
            float(dglm_module._trigamma_safe(argument)),
            1e-12 + 5e-25,
            rtol=_dtype_rtol(1e-10, 1e-6),
        )

    def test_safe_polygammas_are_continuous_at_the_switch(self):
        for offset in (-1.0, 1.0):
            argument = jnp.asarray(dglm_module._ASYMPTOTIC_CUTOFF + offset)
            np.testing.assert_allclose(
                float(dglm_module._digamma_safe(argument)),
                float(digamma(argument)),
                rtol=_dtype_rtol(1e-10, 1e-6),
            )
            np.testing.assert_allclose(
                float(dglm_module._trigamma_safe(argument)),
                float(polygamma(1, argument)),
                rtol=_dtype_rtol(1e-10, 1e-6),
            )

    def test_beta_match_holds_for_large_predictor(self):
        alpha, beta = dglm_module._match_beta_moments(
            jnp.asarray(50.0), jnp.asarray(0.5)
        )
        mean = float(
            dglm_module._digamma_safe(alpha) - dglm_module._digamma_safe(beta)
        )
        variance = float(
            dglm_module._trigamma_safe(alpha) + dglm_module._trigamma_safe(beta)
        )
        np.testing.assert_allclose(mean, 50.0, rtol=_dtype_rtol(1e-8, 1e-5))
        np.testing.assert_allclose(variance, 0.5, rtol=_dtype_rtol(1e-6, 1e-4))

    def test_float32_bernoulli_large_predictor_is_finite(self):
        posterior = smcx.dglm_filter(
            jnp.array([50.0], jnp.float32),
            jnp.array([[0.5]], jnp.float32),
            jnp.eye(1, dtype=jnp.float32),
            jnp.array([1.0], jnp.float32),
            jnp.array([1.0, 0.0, 1.0], jnp.float32),
            family=bernoulli(),
            transition_covariance=jnp.array([[0.01]], jnp.float32),
        )
        for field in posterior:
            assert np.all(np.isfinite(np.asarray(field)))

    def test_large_variance_poisson_match_is_used_by_the_filter(self):
        posterior = smcx.dglm_filter(
            jnp.array([0.0]),
            jnp.array([[100.0]]),
            jnp.eye(1),
            jnp.array([1.0]),
            jnp.array([1.0]),
            family=poisson(),
            transition_covariance=jnp.array([[0.01]]),
        )
        # emissions[0] conditions the prior directly, so the matched
        # variance is F' C0 F = 100 with no evolution contribution.
        prior_alpha = float(posterior.conjugate_alphas[0]) - 1.0
        recovered = float(dglm_module._trigamma_safe(jnp.asarray(prior_alpha)))
        np.testing.assert_allclose(
            recovered, 100.0, rtol=_dtype_rtol(1e-6, 1e-4)
        )


class TestZeroPredictorVariance:
    """A zero prior predictor variance is rejected eagerly (#282)."""

    def test_zero_initial_covariance_is_rejected(self):
        with pytest.raises(ValueError, match="prior variance"):
            smcx.dglm_filter(
                jnp.array([0.5]),
                jnp.array([[0.0]]),
                jnp.eye(1),
                jnp.array([1.0]),
                jnp.array([1.0, 2.0, 0.0]),
                family=poisson(),
                transition_covariance=jnp.array([[0.01]]),
            )

    def test_rank_deficient_direction_is_rejected(self):
        with pytest.raises(ValueError, match="prior variance"):
            smcx.dglm_filter(
                jnp.array([0.0, 0.5]),
                jnp.diag(jnp.array([1.0, 0.0])),
                jnp.eye(2),
                jnp.array([0.0, 1.0]),
                jnp.array([1.0, 2.0, 0.0]),
                family=poisson(),
                transition_covariance=0.01 * jnp.eye(2),
            )


class TestObservationSupport:
    """Built-in families reject out-of-support emissions eagerly (#283)."""

    def _run(self, family, emissions):
        return dglm_filter(
            jnp.array([0.0]),
            jnp.array([[0.5]]),
            jnp.eye(1),
            jnp.array([1.0]),
            jnp.asarray(emissions),
            family=family,
            transition_covariance=jnp.array([[0.01]]),
        )

    def test_poisson_rejects_fractional_and_negative_counts(self):
        with pytest.raises(ValueError, match="nonnegative integer"):
            self._run(poisson(), [0.5, 1.0])
        with pytest.raises(ValueError, match="nonnegative integer"):
            self._run(poisson(), [-1.0, 1.0])

    def test_bernoulli_rejects_fractional_outcome(self):
        with pytest.raises(ValueError, match="integers in"):
            self._run(bernoulli(), [0.5, 1.0])

    def test_binomial_rejects_out_of_range_count(self):
        with pytest.raises(ValueError, match="integers in"):
            self._run(binomial(trials=2), [5.0, 1.0])

    def test_integral_float_emissions_remain_accepted(self):
        posterior = self._run(poisson(), [1.0, 0.0, 3.0])
        assert np.isfinite(float(posterior.marginal_loglik))
        posterior = self._run(binomial(trials=2), [2.0, 0.0])
        assert np.isfinite(float(posterior.marginal_loglik))

    def test_unhashable_callable_field_reaches_inference(self):
        # The boundary reads an attribute from the family's own
        # log_forecast with getattr, so a user callable needs neither
        # hashability nor weak-reference support.
        base = poisson()

        class UnhashableForecast:
            __slots__ = ()
            __hash__ = None

            def __call__(self, emission, alpha, beta):
                return base.log_forecast(emission, alpha, beta)

        forecast = UnhashableForecast()
        with pytest.raises(TypeError):
            hash(forecast)
        with pytest.raises(TypeError):
            weakref.ref(forecast)
        family = base._replace(log_forecast=forecast)
        posterior = self._run(family, [1.0, 0.0])
        assert np.isfinite(float(posterior.marginal_loglik))

    def test_user_defined_family_is_unchecked(self):
        # A user family supplies its own callables, so its
        # log_forecast is not a registered built-in closure and the
        # boundary runs no support check.
        base = poisson()
        family = base._replace(
            log_forecast=lambda y, alpha, beta: base.log_forecast(
                y, alpha, beta
            )
        )
        posterior = self._run(family, [0.5, 1.0])
        assert np.isfinite(float(posterior.marginal_loglik))

    def test_family_record_keeps_the_four_field_sequence_contract(self):
        # The released 2.x contract: a four-element sequence that
        # unpacks positionally (#317).
        family = poisson()
        assert len(family) == 4
        match_moments, log_forecast, update, posterior_moments = family
        assert match_moments is family.match_moments
        assert log_forecast is family.log_forecast
        assert update is family.update
        assert posterior_moments is family.posterior_moments
        assert family._fields == (
            "match_moments",
            "log_forecast",
            "update",
            "posterior_moments",
        )

    @pytest.mark.parametrize("trials", [1.5, True, "2", 0, -3])
    def test_binomial_rejects_non_integer_trials(self, trials):
        # Under the test suite's jaxtyping hook the annotation rejects
        # 1.5 and '2' as TypeCheckError before the runtime ValueError
        # that guards default-config users; both name the parameter.
        with pytest.raises((ValueError, TypeCheckError), match="trials"):
            binomial(trials=trials)


class TestSolverRobustness:
    """The moment solvers converge on moderate valid inputs (R3a, R3b)."""

    @pytest.mark.parametrize("mean", [-30.0, -4.0, 0.0, 4.0, 30.0])
    @pytest.mark.parametrize("variance", [1e-4, 0.5, 20.0, 100.0])
    def test_beta_match_recovers_the_moments(self, mean, variance):
        alpha, beta = dglm_module._match_beta_moments(
            jnp.asarray(mean), jnp.asarray(variance)
        )
        recovered_mean = float(
            dglm_module._digamma_safe(alpha) - dglm_module._digamma_safe(beta)
        )
        recovered_variance = float(
            dglm_module._trigamma_safe(alpha) + dglm_module._trigamma_safe(beta)
        )
        np.testing.assert_allclose(
            recovered_mean, mean, rtol=_dtype_rtol(1e-8, 1e-4), atol=1e-6
        )
        np.testing.assert_allclose(
            recovered_variance, variance, rtol=_dtype_rtol(1e-6, 1e-3)
        )

    def test_public_bernoulli_moderate_prior_is_finite(self):
        posterior = smcx.dglm_filter(
            jnp.array([4.0]),
            jnp.array([[20.0]]),
            jnp.eye(1),
            jnp.array([1.0]),
            jnp.array([1.0, 0.0, 1.0]),
            family=bernoulli(),
            transition_covariance=jnp.array([[0.01]]),
        )
        for field in posterior:
            assert np.all(np.isfinite(np.asarray(field))), field

    def test_float32_inverse_trigamma_survives_tiny_variance(self):
        alpha = dglm_module._inverse_trigamma(jnp.asarray(1e-20, jnp.float32))
        assert np.isfinite(float(alpha))
        wide = jnp.asarray(alpha, jnp.float64)
        recovered = float(dglm_module._trigamma_safe(wide))
        np.testing.assert_allclose(recovered, 1e-20, rtol=1e-4)


class TestSmallVarianceStability:
    """Small predictor variances keep forecast accuracy (R3a, R3c).

    The branch rule prefers the exact conjugate algebra. It takes the
    q -> 0 limit (negative binomial -> Poisson, beta-binomial ->
    binomial) only when the limit's truncation bound falls below a
    calibrated floor of the exact evaluation's rounding error. The
    reference values are 50-digit mpmath evaluations.
    """

    #: (f, q, y, exact nbinom log-pmf), mpmath dps=50
    POISSON_GOLDEN = (
        (1.0, 1e-06, 0, -2.7182794930766446),
        (1.0, 1e-06, 1, -1.7182817113549452),
        (1.0, 1e-06, 5, -2.5057723272701936),
        (0.0, 1e-08, 0, -1.0),
        (0.0, 1e-08, 1, -1.000000005),
        (0.0, 1e-08, 5, -5.7874916677820478),
        (-2.0, 1e-05, 0, -0.13533586833389527),
        (-2.0, 1e-05, 1, -2.1353322217024784),
        (-2.0, 1e-05, 5, -14.922709379958805),
    )

    @pytest.mark.parametrize(
        "mean, variance, emission, expected", POISSON_GOLDEN
    )
    def test_poisson_forecast_matches_mpmath(
        self, mean, variance, emission, expected
    ):
        family = poisson()
        alpha, beta = family.match_moments(
            jnp.asarray(mean), jnp.asarray(variance)
        )
        actual = float(
            family.log_forecast(jnp.asarray(float(emission)), alpha, beta)
        )
        # The limit branch truncates at O(q); the band covers it in
        # both dtypes alongside float32 rounding.
        np.testing.assert_allclose(
            actual, expected, atol=_dtype_rtol(2e-4, 2e-3), rtol=1e-5
        )

    @pytest.mark.parametrize("variance", [1e-4, 1e-6, 1e-8])
    def test_bernoulli_symmetry_invariant(self, variance):
        # f = 0 implies equal matched beta parameters and predictive
        # probability exactly 1/2, regardless of their magnitude.
        family = bernoulli()
        alpha, beta = family.match_moments(
            jnp.asarray(0.0), jnp.asarray(variance)
        )
        log_half = float(family.log_forecast(jnp.asarray(1.0), alpha, beta))
        # Above the crossover the exact branch's cancellation error is
        # about eps / q * log(1/q) relative; below it the limit branch
        # is exact for f = 0. The band covers the worst tested q per
        # dtype.
        np.testing.assert_allclose(
            log_half, -math.log(2.0), rtol=_dtype_rtol(1e-7, 1e-6)
        )

    def test_float32_tiny_variance_poisson_is_finite_and_close(self):
        family = poisson()
        alpha, beta = family.match_moments(
            jnp.asarray(0.0, jnp.float32), jnp.asarray(1e-8, jnp.float32)
        )
        actual = float(
            family.log_forecast(jnp.asarray(1.0, jnp.float32), alpha, beta)
        )
        np.testing.assert_allclose(actual, -1.0, rtol=1e-4)


@pytest.mark.skipif(
    not _CPU_X64, reason="the pre-cast values require a float64 backend"
)
class TestValidationBeforeCast:
    """Support checks see pre-cast values (R8)."""

    def _run(self, emissions):
        return smcx.dglm_filter(
            jnp.array([0.0], jnp.float32),
            jnp.array([[0.5]], jnp.float32),
            jnp.eye(1, dtype=jnp.float32),
            jnp.array([1.0], jnp.float32),
            emissions,
            family=poisson(),
            transition_covariance=jnp.array([[0.01]], jnp.float32),
        )

    def test_near_integer_float64_emission_is_rejected(self):
        # Casting to the float32 state dtype would truncate this to
        # exactly 1.0 and pass integer support.
        with pytest.raises(ValueError, match="nonnegative integer"):
            self._run(jnp.array([1.00000001, 0.0], jnp.float64))

    def test_tiny_negative_float64_emission_is_rejected(self):
        # Casting would flush this to negative zero and pass the
        # nonnegativity check.
        with pytest.raises(ValueError, match="nonnegative integer"):
            self._run(jnp.array([-1e-50, 0.0], jnp.float64))


class TestErrorAwareCrossover:
    """The branch choice tracks the actual error, not q alone (R3a).

    References are 50-digit mpmath evaluations of the exact conjugate
    forecasts. The moderate-intensity and multi-trial cases sit where
    a q-only crossover chose the limit and lost more than a tenth of
    a nat; the error-aware switch must keep the exact algebra there.
    """

    #: (f, q, y, exact nbinom log-pmf)
    POISSON_MODERATE = (
        (6.0, 0.001, 403, -4.0882232570866959),
        (6.0, 0.001, 380, -4.555902852993563),
        (2.0, 0.01, 12, -3.3142847774208137),
        (0.0, 1e-05, 3, -2.791744469532216),
    )

    #: (f, q, trials, y, exact beta-binomial log-pmf)
    BINOMIAL_MODERATE = (
        (0.0, 0.001, 100, 50, -2.5432211861360956),
        (0.0, 0.001, 100, 60, -4.4877197397299169),
        (1.0, 0.01, 20, 10, -4.0556590178591073),
    )

    @pytest.mark.parametrize(
        "mean, variance, emission, expected", POISSON_MODERATE
    )
    def test_poisson_moderate_intensity(
        self, mean, variance, emission, expected
    ):
        family = poisson()
        alpha, beta = family.match_moments(
            jnp.asarray(mean), jnp.asarray(variance)
        )
        actual = float(
            family.log_forecast(jnp.asarray(float(emission)), alpha, beta)
        )
        np.testing.assert_allclose(
            actual, expected, rtol=_dtype_rtol(1e-6, 2e-3)
        )

    @pytest.mark.parametrize(
        "mean, variance, trials, emission, expected", BINOMIAL_MODERATE
    )
    def test_binomial_multi_trial(
        self, mean, variance, trials, emission, expected
    ):
        family = binomial(trials=trials)
        alpha, beta = family.match_moments(
            jnp.asarray(mean), jnp.asarray(variance)
        )
        actual = float(
            family.log_forecast(jnp.asarray(float(emission)), alpha, beta)
        )
        np.testing.assert_allclose(
            actual, expected, rtol=_dtype_rtol(1e-6, 2e-3)
        )


class TestStableMomentDifferences:
    """Representable posterior-moment differences survive (R3b)."""

    def test_bernoulli_recurrence_through_the_filter(self):
        # f=0, q=1e-6, y=1: matched a = b, posterior a* = b* + 1, so
        # the true mean update is digamma(b*+1) - digamma(b*) = 1/b*
        # (the represented recurrence, about 5.0000011e-7); the gain
        # is one, so the filtered mean equals that difference.
        def run():
            return smcx.dglm_filter(
                jnp.array([0.0]),
                jnp.array([[1e-6]]),
                jnp.eye(1),
                jnp.array([1.0]),
                jnp.array([1.0]),
                family=bernoulli(),
                transition_covariance=jnp.array([[1e-12]]),
            )

        eager = float(run().filtered_means[0, 0])
        compiled = float(jax.jit(run)().filtered_means[0, 0])
        family = bernoulli()
        alpha, _ = family.match_moments(jnp.asarray(0.0), jnp.asarray(1e-6))
        # With y = 1 the conjugate update increments alpha, so the mean
        # moves by psi(alpha + 1) - psi(alpha) = 1 / alpha.
        expected = 1.0 / float(alpha)
        np.testing.assert_allclose(
            eager, expected, rtol=_dtype_rtol(1e-4, 1e-2)
        )
        np.testing.assert_allclose(compiled, eager, rtol=1e-6, atol=0.0)


class TestSmallVarianceGradients:
    """Finite public evidence has a finite gradient (R3c)."""

    def test_poisson_limit_gradient_matches_analytic(self):
        def evidence(initial_mean):
            return smcx.dglm_filter(
                initial_mean,
                jnp.array([[1e-8]]),
                jnp.eye(1),
                jnp.array([1.0]),
                jnp.array([1.0]),
                family=poisson(),
                transition_covariance=jnp.array([[0.0]]),
            ).marginal_loglik

        point = jnp.array([1.0])
        value_eager = float(evidence(point))
        grad_eager = float(jax.grad(evidence)(point)[0])
        grad_compiled = float(jax.jit(jax.grad(evidence))(point)[0])

        np.testing.assert_allclose(
            value_eager, 1.0 - math.e - math.lgamma(2.0), rtol=1e-6
        )
        expected_gradient = 1.0 - math.e
        np.testing.assert_allclose(
            grad_eager, expected_gradient, rtol=_dtype_rtol(1e-6, 1e-4)
        )
        np.testing.assert_allclose(
            grad_compiled, expected_gradient, rtol=_dtype_rtol(1e-6, 1e-4)
        )


class TestAbsoluteForecastAccuracy:
    """Public forecasts hold absolute log-score accuracy (R3a).

    References are 80-digit mpmath evaluations of the exact conjugate
    forecasts at the round-3 response review's counterexamples. The
    previous branch rule selected the limit here and lost 0.048 and
    0.0052 nats. Tolerances are absolute nats for the tested dtype.
    """

    def _increment(self, mean, variance, family, emission):
        posterior = smcx.dglm_filter(
            jnp.array([mean]),
            jnp.array([[variance]]),
            jnp.eye(1),
            jnp.array([1.0]),
            jnp.array([float(emission)]),
            family=family,
            transition_covariance=jnp.array([[0.0]]),
        )
        return float(posterior.log_evidence_increments[0])

    @pytest.mark.parametrize(
        "mean, variance, family_fn, emission, expected",
        [
            # mpmath dps=80, matched conjugate forecast log-pmf.
            (6.0, 1e-5, poisson, 303, -17.417682772497664),
            (2.0, 1e-3, lambda: binomial(trials=100), 88, -2.1100522688388537),
        ],
        ids=["poisson-moderate-intensity", "binomial-n100"],
    )
    def test_matches_reference_in_absolute_nats(
        self, mean, variance, family_fn, emission, expected
    ):
        atol = 2e-3 if jnp.asarray(0.0).dtype == jnp.float32 else 1e-8
        eager = self._increment(mean, variance, family_fn(), emission)
        compiled = float(
            jax.jit(
                lambda: smcx.dglm_filter(
                    jnp.array([mean]),
                    jnp.array([[variance]]),
                    jnp.eye(1),
                    jnp.array([1.0]),
                    jnp.array([float(emission)]),
                    family=family_fn(),
                    transition_covariance=jnp.array([[0.0]]),
                ).log_evidence_increments[0]
            )()
        )
        np.testing.assert_allclose(eager, expected, rtol=0.0, atol=atol)
        np.testing.assert_allclose(compiled, expected, rtol=0.0, atol=atol)


class TestDirectionalMomentHelpers:
    """Both moment helpers stay finite in the negative direction (R3b)."""

    @pytest.mark.parametrize(
        "family_fn", [poisson, bernoulli], ids=["poisson", "bernoulli"]
    )
    def test_low_predictor_zero_count_is_finite(self, family_fn):
        posterior = smcx.dglm_filter(
            jnp.array([-17.0]),
            jnp.array([[1e-6]]),
            jnp.eye(1),
            jnp.array([1.0]),
            jnp.array([0.0]),
            family=family_fn(),
            transition_covariance=jnp.array([[0.0]]),
        )
        assert np.isfinite(float(posterior.marginal_loglik))
        assert np.isfinite(float(posterior.filtered_means[0, 0]))


class TestAsymmetricRecurrence:
    """The asymmetric mean update matches its recurrence (R3b)."""

    def test_bernoulli_update_matches_one_over_alpha(self):
        # f = 0.1, q = 1e-6, y = 1, unit gain. With y = 1 the update
        # increments alpha, so the filtered mean equals the
        # represented predictor mean at the matched parameters plus
        # psi(alpha + 1) - psi(alpha) = 1 / alpha. Comparing against
        # the represented mean (the same digamma difference the
        # matcher and posterior now share) cancels the matcher's
        # log-space residual, which in float32 has the same scale as
        # the increment itself.
        def run():
            return smcx.dglm_filter(
                jnp.array([0.1]),
                jnp.array([[1e-6]]),
                jnp.eye(1),
                jnp.array([1.0]),
                jnp.array([1.0]),
                family=bernoulli(),
                transition_covariance=jnp.array([[0.0]]),
            ).filtered_means[0, 0]

        family = bernoulli()
        alpha, beta = family.match_moments(jnp.asarray(0.1), jnp.asarray(1e-6))
        represented_mean = float(
            dglm_module._digamma_difference_safe(alpha, beta)
        )
        expected = represented_mean + 1.0 / float(alpha)

        eager = float(run())
        compiled = float(jax.jit(run)())
        # Eager evaluation shares the test helpers' arithmetic, so the
        # comparison is tight. Compilation may fuse the solver's
        # series arithmetic differently and land one ulp of
        # log(alpha) away on the matched-parameter grid, which moves
        # the mean by about eps * log(alpha); the compiled band is
        # that grid step.
        float32 = jnp.asarray(0.0).dtype == jnp.float32
        tight = 5e-8 if float32 else 1e-10
        grid = (
            4.0
            * float(jnp.finfo(jnp.asarray(0.0).dtype).eps)
            * math.log(float(alpha))
        )
        np.testing.assert_allclose(eager, expected, rtol=0.0, atol=tight)
        np.testing.assert_allclose(
            compiled, expected, rtol=0.0, atol=max(grid, tight)
        )
