name: Deploy Documentation

on:
  workflow_run:
    workflows: [Release]
    types: [completed]
    branches: [main]
  workflow_dispatch:

# Sets permissions to allow deployment to GitHub Pages
permissions:
  contents: write

jobs:
  deploy-docs:
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0

      - name: Setup uv
        uses: ./.github/actions/setup-uv
        with:
          locked: 'false'

      - name: Deploy to GitHub Pages
        run: uv run properdocs gh-deploy --force
